platform:ios,'8.0'
target 'HaloKitProduct' do

  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.2.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'CocoaAsyncSocket', '~> 7.6.1'
  pod 'Getui', '~> 1.6.2.0'
end
