platform:ios,'8.0'
target 'HaloKitProduct' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'AFNetworking', '~> 3.1.0'
   pod 'CocoaAsyncSocket'

end
